mysite/djangogirl/urls.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'djangogirl'
urlpatterns = [
	# url(r'^post/\d+/$', views.post_list, name='post_list')
	url(r'^$', views.post_list, name='post_list'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^post/(?P<pk>[0-9]+)/edit/$',views.post_edit,name='post_edit'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('djangogirl.urls')),
    # url(r'^blog/',include('djangogirl.urls'))
]

mysite/djangogirl/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True,null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __unicode__(self):
		return self.title

mysite/djangogirl/forms.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-

from django import forms

from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title','text')

mysite/djangogirl/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import Post
from django.utils import timezone
from .forms import PostForm
import urlparse

# Create your views here.

# def post_list(request,id):
# 	return HttpResponse('you are look at %s' % id)


def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	# paginator = Paginator(posts,5)
	# try:
	# 	topics = paginator.page(page)
	# except PageNotAnInteger:
	# 	topics =paginator.page(1)
	# except EmptyPage:
	# 	topics = paginator.page(paginator.num_pages)
	return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
	posts = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {'posts': posts})


def post_new(request):
	if request.method == 'POST':
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			# return redirect(reverse('post_list'))
			url = urlparse.urljoin('/post/', str(post.pk))
			return redirect(url)
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request,pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		form = PostForm(request.POST,instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			# return redirect(reverse('post_list'))
			url = urlparse.urljoin('/post/', str(post.pk))
			return redirect(url)
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html', {'form': form})

mysite/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
    <title>django girl blog</title>
</head>
<body>
    <div class="page-header">
        {% if user.is_authenticated %}
            <a href="{% url 'djangogirl:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        {% endif %}
        <h1><a href="{% url 'djangogirl:post_list' %}">Django Girl Blog</a> </h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

mysite/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}


<div class="post">
    <h1>{{ posts.title }}</h1>
    {% if posts.published_date %}
     <div class="date">
     {{ posts.published_date }}
     </div>
    {% endif %}
    <a class="btn btn-default" href="{% url 'djangogirl:post_edit' pk=posts.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
    <p>{{ posts.text|linebreaksbr }}</p>
</div>
{% endblock %}

mysite/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New Post</h1>
    <form method="post" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mysite/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
        <h1><a href="{% url 'djangogirl:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <div class="date">
            <p>publish: {{ post.published_date }}</p>
        </div>

        <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}